name: Build Engine

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update && sudo apt install -y python3 make build-essential clang \
          mesa-common-dev libgl1-mesa-dev libglu1-mesa-dev bash upx \
          gcc-mingw-w64 libasound2-dev wget

    - name: Build engine Linux (Compressed)
      run: |
        make clean
        CC=clang make strip
        mkdir -p ci_build
        cp -r build/ ci_build/
        make clean tools
        cp -r build/ ci_build/

    - name: Build engine Windows
      run: |
        make clean
        CC=x86_64-w64-mingw32-gcc CLANG=0 OS=windows BIN_NAME="potetre2d-sdl2" AUDIO_BACKEND="sdl2" make prepare potetre2d strip
        mkdir -p ci_build
        cp -r build/ ci_build/
        CC=x86_64-w64-mingw32-gcc CLANG=0 OS=windows make clean tools
        cp -r build/ ci_build/
        wget https://github.com/libsdl-org/SDL/releases/download/release-2.26.5/SDL2-2.26.5-win32-x64.zip -O ci_build/SDL2-2.26.5-win32-x64.zip
        cd ci_build;unzip SDL2-2.26.5-win32-x64.zip && rm *.zip

    - name: Add licenses and other files
      run: |
        ./scripts/gen_license.sh > ci_build/LICENSE.txt
        cp README.md ci_build/
        cp -r doc/ ci_build/
        cp -r examples/ ci_build/

    - uses: actions/upload-artifact@v3
      with:
        name: engine_bin
        path: |
          ci_build/
