name: Build Engine

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update && sudo apt install -y python3 make build-essential clang \
          mesa-common-dev libgl1-mesa-dev libglu1-mesa-dev bash upx \
          gcc-mingw-w64

    - name: Build engine Linux (Compressed)
      run: |
        make clean
        ./bootstrap.sh
        CC=clang make compress
        make -p linux
        cp -r build/ linux/

    - name: Build engine Windows
      run: |
        make clean
        ./bootstrap.sh
        CC=x86_64-w64-mingw32-gcc CLANG=0 OS=Windows_NT make
        make -p windows
        cp -r build/ windows/

    - uses: actions/upload-artifact@v3
      with:
        name: engine_bin
        path: |
          build/
